spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rnc?currentSchema=public
    username: postgres
    password: 123456



#    url: jdbc:postgresql://pgsqlqacl1.naiss.local:5432/rnc?currentSchema=public
#    username: adm_rnc
#    password: kZ4syEjf
